### ISSUE TITLE
Print functions

### ISSUE THREAD

**Issue by janrutger** [acgeospatial/SVM_digits#1]
Many thanks for this easy example for raspberry, as starter on ML very helpfull, but..... 
Non of the print commands are working, on all lines wrong placed or missing  ( and ) 

line 17:
print ("time to import libraries: ", time.time() - time_start)

line 35:
print ("SVM predicts this number: ", clf.predict(digits.data[[-i]]))

line 41:
print ("time to train data set, run SVM and make prediction: ", time.time() - time_start2)

**Comment by acgeospatial** [comment]
I've removed the time calls and the code runs for me on a desktop PC. 
![image](https://user-images.githubusercontent.com/20108023/145674479-337d6991-22ab-4c86-a034-d6b95a5d4aee.png)
